### ISSUE TITLE
Link to hosted x-element build in README

### ISSUE THREAD

**Issue by klebba** [Netflix/x-element#105]
I'm not sure what the best options are lately, but something like this could help fast adoption & fiddling:

https://unpkg.com/browse/@netflix/x-element@1.0.0-rc.49/x-element.js

**Comment by theengineear** [comment]
@klebba — Couple questions:

* Should we merge [SPEC.md](SPEC.md) into [README.md](README.md)? There is an example of importing from `unpkg` there that should currently work.
* Should we open up an issue ticket to discuss the "best practice" for packaging an ES6-importable module in the age of "import maps"? I think nailing down the right file structure which will play well with import maps is critical (and perhaps we already have).

**Comment by klebba** [comment]
My personal preference would be to link to SPEC.md and ensure that README.md remains more of an overview/elevator pitch

Let's definitely discuss best practice for integration, maybe even spinning off a USAGE.md or something with the result?

**Comment by klebba** [comment]
Minor aside — SPEC.md could update its references to Lit — it's `https://lit.dev` now

**Comment by theengineear** [comment]
>Let's definitely discuss best practice for integration, maybe even spinning off a USAGE.md or something with the result?

Sure, I think the "best practice" assuming that we're now living in the "import maps" future would be a good conversation to have.

**Comment by theengineear** [comment]
@klebba — as part of #116, I'm updating the `README.md` to point to `import XElement from 'https://deno.land/x/element/x-element.js';`. I'm going to mark #116 as closing this ticket once it's merged.
