### ISSUE TITLE
Publish a playground for simple fiddling with “x-element”.

### ISSUE THREAD

**Issue by theengineear** [Netflix/x-element#113]
We should host static page (perhaps within the GitHub ecosystem) to allow fiddling with “x-element”. It'd be interesting to see how light-weight a solution we could come up with which would still essentially give folks a light-weight text editor and rendered output.

Not sure on exactly the where / how yet, but I think this would be valuable to lower the barrier-to-entry.

**Comment by theengineear** [comment]
@klebba — Not sure if you've thought about this one too much, but it might be a fun little project to knock out.

**Comment by codeStryke** [comment]
If we make x-element play nice with build tools then we rely on existing playgrounds like [codepen](https://codepen.io/), [jsfiddle](https://jsfiddle.net/), [stackblitz](https://stackblitz.com/), [glitch](https://glitch.com/) etc.

**Comment by theengineear** [comment]
If we merge #116, that should become a lot easier. We'll have _zero_ dependencies so questions around the location of sibling dependencies would just go away.
