### ISSUE TITLE
Collecting 1.0 release tasks

### ISSUE THREAD

**Issue by klebba** [Netflix/x-element#154]
- Audit documentation
- Audit tests
- Audit package.json dev dependencies (#158)
- Migrate from Yarn to NPM (#163)
- Publish x-test 1.0 (see [here](https://github.com/Netflix/x-element/blob/main/test/x-test.js#L2))
- Kick off CHANGELOG.md
- what else?

**Comment by theengineear** [comment]
Maybe moving from `yarn` >> `npm`? I feel like we aren’t getting major benefits from `yarn` anymore, right?

**Comment by theengineear** [comment]
Maybe create a test / demo of using Form-Associated Custom Elements?

**Comment by theengineear** [comment]
Maybe demo React 19 interoperation?

**Comment by theengineear** [comment]
Might be worthwhile to tackle #128 in here — error causes for chaining.

**Comment by klebba** [comment]
All great suggestions — IMO unless they change the public interface these changes would be ok to land as patch or minor versions (e.g. `1.0.1` or `1.1.0`)

**Comment by theengineear** [comment]
🤔 – Another thing that I have wanted to investigate is how “decorators” (currently Stage 3 in TC39) may impact the property pipeline. That proposal is starting to feel stable enough to warrant a deeper look now IMO.

In particular, I want to explore whether it might change our mind about “internals” ergonomics (especially as it relates to truly private constructor and prototype methods).

The latest proposal tries really hard to ensure that  upfront, static class analysis will work – which is critical to the “properties” and “listeners” configuration.

Mostly, I just want to understand what the deprecation cycle would look like later if we tried to migrate from our current interface to one with decorators.

I may try and look into that one if I find a little time.

**Comment by klebba** [comment]
@theengineear now that 1.0 is published should we open independent issue tickets regarding the items we deferred?
