### ISSUE TITLE
Discussion: Should we allow a “Node” as content.

### ISSUE THREAD

**Issue by theengineear** [Netflix/x-element#207]
**Current**

```js
const container = document.createElement('div');
const input = document.createElement('input');
render(container, html`${input}`);
// <div>[object HTMLInputElement]</div>
```

We _could_ handle `Node`s in a special manner where we just bind the live value directly as content. We would also want to consider whether a `Node` would be allowed as a value of an array.

**Pros**
* Just let me do the thing!

**Cons**
* Added complexity / surface area to maintain.
* Could invite bad practices.
* Typically easy to work around (create a template or use `observe`).

**Comment by theengineear** [comment]
💡 — Another option here would be to enable some sort of syntax that could act as a “callback when instantiated”. Either way, this ticket is really about gaining references to nodes to leverage imperative apis. Here’s an example of what that might look like:

```js
const callback = node => {
  node.addEventListener('change', () => console.log('changed!'));
}
html`<input(${callback})>`; // The “callback” method is called when the `input` is created.
```

**Comment by klebba** [comment]
Note that if a DOM node binding is reused within a template only the last occurrence will actually be displayed (because copies of the Node will not occur)
