### ISSUE TITLE
Upgrade to lit-html 2.0 after stable release

### ISSUE THREAD

**Issue by reliable-casey** [Netflix/x-element#75]
https://github.com/Polymer/lit-html/blob/lit-next/packages/lit-html/CHANGELOG.md

**Comment by klebba** [comment]
Hey @theengineear, hoping we can start looking into this together. No specific urgency, just don't want to fall too far behind. Lit 2.0 changes look minimal —  https://lit.dev/docs/releases/upgrade/ — main issue will be this:

> Although the lit-element@^3 and lit-html@^2 packages should be largely backward-compatible, we recommend updating to the lit package as the other packages are moving towards eventual deprecation.

`import {LitElement, html} from 'lit';`

My intuition is to change XElement if and when Lit actually breaks this compatibility. It would seem bizarre to import LitElement with XElement in any eventuality. Instead we may prefer to either replace `lit-html` or use an older version until the browser itself stops supporting it.
