### ISSUE TITLE
Property definition "initial" value is unexpectedly reused across instances

### ISSUE THREAD

**Issue by klebba** [Netflix/x-element#89]
For example, given an element `x-baz` with property block as follows:

```
static get properties() {
  return {
    bar: {
        type: Foo,
        initial: () => new Foo(),
    },
  };
}
```

Newly created instances of `<x-baz>` will reuse the same instance of `Foo`. In my case this creates an issue when attempting to destroy unwanted copies of `x-baz`. Because the reference is shared, any newly created `<x-baz>` will point to the original `Foo`

Happy to create a repro case if it helps

**Comment by theengineear** [comment]
Seems reasonable. I'll update.
