### ISSUE TITLE
Allow typeless properties to be set via an attribute.

### ISSUE THREAD

**Issue by theengineear** [Netflix/x-element#99]
The goal of typeless properties is to _just let me do it_. In this case, while it still doesn't make sense to `reflect` a typeless property, it's reasonable to allow an attribute to sync down to a typeless property.

I.e., consider the following element ...

```js
const MyElement extends XElement {
  static get properties() {
    return { data: {} };
  }
  static template(html) {
    return ({ data }) => html`<span>Here is some data: ${data}.</span>`;
  }
}
customElements.define('my-element', MyElement);
```

... I'd expect to be able to do the following ...

```html
<my-element data="123"></my-element>
```

Such that the output would read as:

```
Here is some data: 123.
```

However, because the property is typeless, "123" will never be synced from the _attribute_ to the _property_.

**Comment by klebba** [comment]
@theengineear can you give a more tangible example where this is needed? In the example provided it seems that it would be appropriate to use `String` as the type, given that all attributes are strings. That said, I totally agree with the rationale for the change — if `x-element` is in your way we should address this

**Comment by theengineear** [comment]
Hey @klebba, the tangible example is for a component we use in our application which allows a user to update profile storage. This component allows integrators to bind arbitrary `onData` and `offData` for toggling. In some cases, the on/off data is 100% known before time and is more readable when bound as an attribute (since it's a string):

```
<profile-storage-toggle key="keep-it-real" on-data="always" off-data="never"></profile-storage-toggle>
```

However, some data is actually typed for [reasons] and ends up being meta-programmed into existence:

```
<profile-storage-toggle .key="${storage.key}" .onData="${storage.onData}" .offData="${storage.offData}"></profile-storage-toggle>
```

It's because of this latter case that we want the property to be _typeless_. However, the usability of the former case is desirable. As a workaround, I've temporarily specified the properties block as follows:

```
  static get properties() {
    return {
      key: {
        type: String,
      },
      data: {},
      // This allows be to bind both "on-data"  and "off-data" attributes. I want to be able to delete this hack.
      _attrOnData: { type: String, attribute: 'on-data', observe: (host, value) => { host.onData = value; } },
      _attrOffData: { type: String, attribute: 'off-data', observe: (host, value) => { host.offData = value; } },
      onData: {},
      offData: {},
    };
  }
```

**Comment by klebba** [comment]
This is actually sounding more like a bug fix than a change of function. I'm not fully following the second example but I'm not sure this is necessary. I'll try to repeat back my understanding:

Current function:
* property declarations without a type behave differently than property declarations with a type — in particular, a value which typically would forward from an attribute to a property value does not do this if the property has no type

Desired function:
* attribute -> property flow should always behave consistently regardless of the type (or lack of type) specified in the property declaration

Is that right?

**Comment by theengineear** [comment]
☝️ — I think that this explanation leaves out an important fork in behavior related to *whether or not a property is serializable based on the declared type*.

**Current Function**

* If a property type is serializable — sync attribute to property (e.g., `"5" >> 5`) and allow reflection.
* If a property type is not specified — don't sync attribute to property and prevent reflection.
* If a property type is not serializable — don't sync attribute to property and prevent reflection.

**Desired Function**

* If a property type is serializable — sync attribute to property (e.g., `"5" >> 5`) and allow reflection.
* ~If a property type is not specified — don't sync attribute to property and prevent reflection.~
* If a property type is not specified — sync attribute to property _as is_ (e.g., `"5" >> "5"`) but prevent reflection.
* If a property type is not serializable — don't sync attribute to property and prevent reflection.

**Explanation**

Omitting the `type` doesn't mean that a property _doesn't have a type_ — it means the property _may have any type_. Because attributes are always strings, and a typeless property may be set to a string value, we should allow syncing to such properties.

**Comment by klebba** [comment]
So another way to state this would be "when a property declaration has no specified type, all attribute->property synchronization will default to the `String` type" — is that right? Why would reflection be prevented in this case?

**Comment by theengineear** [comment]
Yep. I think we're on the same page there.

>Why would reflection be prevented in this case?

We cannot reflect here because we cannot guarantee serialization. Here's an example:

```js
element.typelessProperty = 'foo'; // ok, we could try to reflect to [typeless-property="foo"]
element.typelessProperty = new FizzBuzz(7, 8, 9); // hmm... what the heck do we do now?
```

**Comment by klebba** [comment]
Gotcha — do we currently warn the developer when they add reflection to a typeless property?

**Comment by theengineear** [comment]
>Do we currently warn the developer when they add reflection to a typeless property?

We error during the analysis phase on this one since we currently consider it a misconfiguration.

```
Found unserializable "MarkdownElement.properties.typeless.type" (Undefined) but "MarkdownElement.properties.typeless.reflect" is true.
```

**Comment by theengineear** [comment]
@klebba — Just a quick ping on this (as it relates to #100). If you want to discuss further, we can always cut a release with what we've got now and let this move into a subsequent release (or not if we decide it's not the right behavior).

**Comment by klebba** [comment]
Oops, sorry I left ya hanging. I'm totally on board with the change, thanks for explaining it in so much detail!
